### ISSUE TITLE
Hoogle returns 200 OK for parse error

### ISSUE THREAD

**Issue by LordAro** [HackSoc/csbot#78]
https://code.google.com/p/ndmitchell/issues/detail?id=645

Causes an internal exception, as the JSON is different to expected

Debatable whether this is hoogle's (the plugin) problem or not (especially if it doesn't get fixed)

**Comment by alanbriolat** [comment]
I've come around to thinking that it's actually acceptable to return a 200 for a response like this - it's not entirely clear what the status code should be otherwise. It also looks like Hoogle will never change it. The response is not too hard to handle: check for ``results`` key, if not present check for ``parseError`` key, and then default to unspecified error. Nice easy fix.
